iReports/src/main/java/com/pradera/report/generation/executor/account/PortafolioDetailCustodianBean.java
package com.pradera.report.generation.executor.account;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.enterprise.inject.Instance;
import javax.inject.Inject;

import org.apache.commons.lang3.StringUtils;

import com.pradera.commons.contextholder.interceptor.LoggerAuditWeb;
import com.pradera.commons.contextholder.interceptor.LoggerCreateBean;
import com.pradera.commons.report.ReportUser;
import com.pradera.commons.sessionuser.UserInfo;
import com.pradera.commons.utils.CommonsUtilities;
import com.pradera.commons.utils.GeneralConstants;
import com.pradera.commons.utils.JSFUtilities;
import com.pradera.commons.utils.PropertiesUtilities;
import com.pradera.commons.view.GenericBaseBean;
import com.pradera.commons.view.ViewDepositaryBean;
import com.pradera.core.component.generalparameter.service.ParameterServiceBean;
import com.pradera.core.component.generalparameter.to.ParameterTableTO;
import com.pradera.core.component.helperui.facade.HelperComponentFacade;
import com.pradera.core.component.helperui.to.HolderHelperOutputTO;
import com.pradera.core.component.helperui.to.SecuritiesSearcherTO;
import com.pradera.core.component.helperui.to.SecuritiesTO;
import com.pradera.integration.common.type.BooleanType;
import com.pradera.integration.common.validation.Validations;
import com.pradera.integration.exception.ServiceException;
import com.pradera.model.accounts.type.EconomicActivityType;
import com.pradera.model.generalparameter.ParameterTable;
import com.pradera.model.generalparameter.type.MasterTableType;
import com.pradera.model.report.type.ReportFormatType;
import com.pradera.report.generation.executor.account.service.AccountReportServiceBean;
import com.pradera.report.generation.executor.account.to.PortafolioDetailCustodianTO;
import com.pradera.report.generation.facade.ReportGenerationLocalServiceFacade;
import com.pradera.report.util.view.PropertiesConstants;

@ViewDepositaryBean
@LoggerCreateBean
public class PortafolioDetailCustodianBean extends GenericBaseBean implements Serializable{
	private static final long serialVersionUID = 1L;
	
	@EJB
	private ParameterServiceBean parameterService;
	@EJB
	private AccountReportServiceBean accountReportService;
	@EJB
	private HelperComponentFacade helperComponentFacade;
	@EJB
	private ReportGenerationLocalServiceFacade reportGenerationFacade;
	@Inject
	private UserInfo userInfo;	
	@Inject
	Instance<PortafolioDetailCustodianReport>  pdcReport;
	
	private static final String CONFIRM_DIALOG_SUCCESS=":frmCustodyDetail:reportGenerationOk";
	
	private ReportUser reportUser;
	private List<ParameterTable> reportFormats;
	private List<ParameterTable> lstEconomicActivity;
	private List<HolderHelperOutputTO> lstAllFundType;
	private List<HolderHelperOutputTO> lstFoundCUI;
	private HolderHelperOutputTO holderHelper;
	private String FCC="FCC";
	private String FCI="FCI";
	private String FRD="FRD";
	private boolean blAFPDisabled;
	private boolean blInsuranceDisabled;
	private Long reportId=new Long(4);
	
	public PortafolioDetailCustodianBean() {
		blAFPDisabled=true;
		blInsuranceDisabled=true;
		SecuritiesTO security= new SecuritiesTO();
		holderHelper = new HolderHelperOutputTO();
		holderHelper.setDate(new Date());
		holderHelper.setSecurityTO(security);
	}
	
	@PostConstruct
	public void init(){
		loadActivityEconomic();
		loadReportFormat();
		holderHelper.setLstFundType(fillFunds());
		getFundCUI();
		reportUser= new ReportUser();
	}

	public void loadReportFormat(){
		ParameterTableTO parameterFilter = new ParameterTableTO();
		parameterFilter.setState(BooleanType.YES.getCode());
		List<Integer> lstParamPk = new ArrayList<Integer>();
		lstParamPk.add(ReportFormatType.TXT.getCode());
		lstParamPk.add(ReportFormatType.PDF.getCode());
		parameterFilter.setLstParameterTablePk(lstParamPk);
		reportFormats = parameterService.getListParameterTableServiceBean(parameterFilter);
	}
	
	public void loadActivityEconomic(){
		List<Integer> lstPks= fillEconomicActivity();
		ParameterTableTO parameterFilter = new ParameterTableTO();
		parameterFilter.setState(BooleanType.YES.getCode());
		parameterFilter.setLstParameterTablePk(lstPks);
		lstEconomicActivity = parameterService.getListParameterTableServiceBean(parameterFilter);
		holderHelper.setLstEconomicActivity(lstPks);
	}
	
	public void getFunds(){
		lstAllFundType = new ArrayList<HolderHelperOutputTO>();
		List<HolderHelperOutputTO> listFundTypes = new ArrayList<HolderHelperOutputTO>();
		HolderHelperOutputTO fundType= new HolderHelperOutputTO();
		if(EconomicActivityType.ADMINISTRADORAS_FONDOS_PENSIONES.getCode().equals(this.holderHelper.getEconomicActivity())){
			fundType.setLstFundType(fillFunds());
			blAFPDisabled=false;
			blInsuranceDisabled=false;
			//fill static comboBox
			for(String ft: fundType.getLstFundType()){
				fundType= new HolderHelperOutputTO();
				fundType.setEconomicActivity(EconomicActivityType.ADMINISTRADORAS_FONDOS_PENSIONES.getCode());
				fundType.setStrFundType(ft);
				listFundTypes.add(fundType);
			}
			lstAllFundType.addAll(listFundTypes);
			holderHelper.setLstEconomicActivity(null);
			holderHelper.setLstFundType(null);
			getFundCUI();
		}else if(EconomicActivityType.COMPANIAS_SEGURO.getCode().equals(this.holderHelper.getEconomicActivity())){
			holderHelper.setEconomicActivity(EconomicActivityType.COMPANIAS_SEGURO.getCode());
			holderHelper.setLstEconomicActivity(null);
			holderHelper.setLstFundType(null);
			holderHelper.setStrFundType(null);
			blAFPDisabled=false;
			blInsuranceDisabled=true;
			getFundCUI();
		}else{
			blAFPDisabled=true;
			blInsuranceDisabled=true;
			holderHelper.setLstEconomicActivity(fillEconomicActivity());
		}
	}
	
	public List<Integer> fillEconomicActivity(){
		List<Integer> lstPks= new ArrayList<Integer>();
		lstPks.add(EconomicActivityType.ADMINISTRADORAS_FONDOS_PENSIONES.getCode());
		lstPks.add(EconomicActivityType.COMPANIAS_SEGURO.getCode());
		
		return lstPks;
	}
	
	private List<String> fillFunds(){
		List<String> lstFunds= new ArrayList<String>();
		
		lstFunds.add(FCC);
		lstFunds.add(FCI);
		lstFunds.add(FRD);

		return lstFunds;
	}

	public void getFundCUI(){
		lstFoundCUI = new ArrayList<HolderHelperOutputTO>();
		holderHelper.setFundCUI(null);
		try {
			List<Object[]> list = accountReportService.getHoldersByFilter(holderHelper);
			HolderHelperOutputTO hhoTO= null;
			for(Object[] temp: list){
				hhoTO = new HolderHelperOutputTO(); 
				if(temp[0]!=null){
					hhoTO.setStrFundType(temp[0].toString());
				}
				if(temp[1]!=null){
					hhoTO.setFullName(temp[1].toString());
				}
				hhoTO.setFundCUI(Long.valueOf(temp[2].toString()));
				
				lstFoundCUI.add(hhoTO);
			}
		} catch (ServiceException e) {
			e.printStackTrace();
		}
	}
	
	public void searchSecurityByCode() throws ServiceException{
		String idSecurity = holderHelper.getSecurityTO().getSecuritiesCode();
		if(StringUtils.isNotBlank(idSecurity)){
			SecuritiesSearcherTO  searcher = new SecuritiesSearcherTO();
			searcher.setIsinCode(idSecurity);
			List<SecuritiesTO>  securityList = helperComponentFacade.findSecuritiesFromHelperNativeQuery(searcher);
			if(!securityList.isEmpty()){
				holderHelper.setSecurityTO(securityList.get(0));
			} else {
				JSFUtilities.showMessageOnDialog(PropertiesUtilities.getGenericMessage(GeneralConstants.LBL_HEADER_ALERT_WARNING), 
									PropertiesUtilities.getGenericMessage(GeneralConstants.HELPER_SECURITY_NOT_FOUND));
				JSFUtilities.showSimpleValidationDialog();
				holderHelper.getSecurityTO().setSecuritiesCode(null);
				holderHelper.getSecurityTO().setDescription(null);
			}
		} else {
			holderHelper.getSecurityTO().setSecuritiesCode(null);
			holderHelper.getSecurityTO().setDescription(null);
		}
	}
	
	@LoggerAuditWeb
	public String submitForm() {
		Map<String,String> parameters = new HashMap<String, String>();
		Map<String,String> parameterDetails = new HashMap<String, String>();
		
		reportUser.setUserName(userInfo.getUserAccountSession().getUserName());
		//how report is send for screen so for default send notification
		reportUser.setShowNotification(BooleanType.YES.getCode());
		try {
			if(Validations.validateIsNotNullAndPositive(reportId)){
				if(Validations.validateIsNullOrEmpty(holderHelper.getStrFundType()) && EconomicActivityType.AFP.getCode().equals(holderHelper.getEconomicActivity())){
					holderHelper.setLstFundType(fillFunds());
				}else if(Validations.validateIsNullOrNotPositive(holderHelper.getEconomicActivity())){
					holderHelper.setLstEconomicActivity(fillEconomicActivity());
				}
				List<Object[]> list = accountReportService.getHoldersByFilter(holderHelper);
				HolderHelperOutputTO hhoTO= null;
				for(Object[] temp: list){
					hhoTO = new HolderHelperOutputTO(); 
					if(temp[0]!=null){
						hhoTO.setStrFundType(temp[0].toString());
					}
					if(temp[1]!=null){
						hhoTO.setFullName(temp[1].toString());
					}
					hhoTO.setFundCUI(Long.valueOf(temp[2].toString()));
					if(temp[3]!=null){
						hhoTO.setEconomicActivity(new BigDecimal(temp[3].toString()).intValue());
					}
					if(temp[4]!=null){
						hhoTO.setDocumentType(((BigDecimal)temp[4]).intValue());
					}
					if(temp[5]!=null){
						hhoTO.setDocumentNumber(temp[5].toString());
					}
					if(temp[6]!=null){
						hhoTO.setTransferNumber(temp[6].toString());
					}
					hhoTO.setSecurityTO(new SecuritiesTO());
					hhoTO.getSecurityTO().setSecuritiesCode(holderHelper.getSecurityTO().getSecuritiesCode());
					hhoTO.setDate(holderHelper.getDate());
					parameters = getCustomJasperParameters(hhoTO);
					reportGenerationFacade.saveReportExecution(reportId, parameters, parameterDetails, reportUser);
				}
				if(list.isEmpty()){//send an empty map parameters
					parameters = getCustomJasperParameters(holderHelper);

iReports/src/main/webapp/pages/acccounts/custodyDetailAFPAndInsuranceReport.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:pe="http://primefaces.org/ui/extensions"
	xmlns:ark="http://java.sun.com/jsf/composite/privilegesPanel"
	xmlns:arkHelp="http://java.sun.com/jsf/composite/helperExtension">

<ui:composition template="/template/default.xhtml">
<ui:define name="body">
<style type="text/css">
.ui-datatable tbody td{searchHolderByCode
	white-space: normal !important;
}
</style>
	<h:outputText value="#{msgs['title.Report']}" styleClass="title-page" id="idTitle"/>
	<h:form id="frmCustodyDetail">
		<table width="100%">
			<tr>
				<td>
					<p:fieldset legend="#{msgs['lbl.custody.detail.afp.and.insurance.legend']}" id="fsMainLegend">
						<table width="100%" border="0"> 
							<tr>
								<td width="130px">
									<h:outputText value="#{msgs['lbl.format.report']}" />
								</td>
								<td width="450px">
									<p:selectOneMenu value="#{portafolioDetailCustodianBean.reportUser.reportFormat}">
										<f:selectItems value="#{portafolioDetailCustodianBean.reportFormats}" var="format" 
													   itemLabel="#{format.parameterName}" itemValue="#{format.parameterTablePk}"/>
									</p:selectOneMenu>
								</td>
							</tr>
							<tr>
								<td>
									<h:outputText value="#{msgs['lbl.custody.detail.afp.and.insurance.security.code']}" id="otSecurityPk"/>
								</td>
								<td>
									<h:panelGrid columns="3">
										<p:inputText id="itSecurity" size="15" maxlength="12" widgetVar="wvSecurity" 
													 value="#{portafolioDetailCustodianBean.holderHelper.securityTO.securitiesCode}">
											<p:keyFilter regEx="#{gconst['helper.securities.alphanumeric.not.space']}" preventPaste="false"/>
											<p:ajax event="blur" partialSubmit="true" process="@this" update="itSecurity, itSecDesc"
													listener="#{portafolioDetailCustodianBean.searchSecurityByCode()}"/>
										</p:inputText>
										<p:outputPanel id="securitiesHelper">
											<arkHelp:security security="#{portafolioDetailCustodianBean.holderHelper.securityTO}" process="@this"
															  update="frmCustodyDetail:itSecurity frmCustodyDetail:itSecDesc"/>
										</p:outputPanel>
										<p:inputText size="40" id="itSecDesc" disabled="true"
													 value="#{portafolioDetailCustodianBean.holderHelper.securityTO.description}" />
									</h:panelGrid>
								 </td>
							</tr>
							
							<tr>
								<td>
									<h:outputText value="#{msgs['lbl.custody.detail.afp.and.insurance.economic.act']} (*)" styleClass="required-field" id="otEconomicActivity"/>
								</td>
								<td>
									<h:panelGrid columns="2">
										<p:selectOneMenu id="somEconomicActivity" style="width:310px" label="#{msgs['lbl.custody.detail.afp.and.insurance.economic.act']}"
														 value="#{portafolioDetailCustodianBean.holderHelper.economicActivity}">
											<f:selectItem itemLabel="#{msgs['cbo.opt.all']}"/>
											<f:selectItems id="siEconomicActivity" value="#{portafolioDetailCustodianBean.lstEconomicActivity}"
														   var="economicAct" itemLabel="#{economicAct.description}" itemValue="#{economicAct.parameterTablePk}"/>
											<p:ajax event="change" update="somFundType, somFundCUI, msgEconomicActivity" listener="#{portafolioDetailCustodianBean.getFunds()}"/>	
											<f:validator validatorId="com.pradera.commons.view.validators.SelectOneMenuValidator" />
										</p:selectOneMenu>
										<p:message id="msgEconomicActivity" for="somEconomicActivity" display="icon" />	
									</h:panelGrid>
															
								</td>
								
								<td width="130px">
									<h:outputText value="#{msgs['lbl.custody.detail.afp.and.insurance.fund.type']} (*)" styleClass="required-field" id="otFundType"/>
								</td>
								<td>
									<h:panelGrid columns="2">
									<p:selectOneMenu id="somFundType" value="#{portafolioDetailCustodianBean.holderHelper.strFundType}" 
													 label="#{msgs['lbl.custody.detail.afp.and.insurance.fund.type']}"
													 style="width:310px" disabled="#{portafolioDetailCustodianBean.blInsuranceDisabled}">
										<f:selectItem itemLabel="#{msgs['cbo.opt.all']}" id="siFundType" />
										<f:selectItems id="idCboItemsBusinessProcSearchLevelOne" value="#{portafolioDetailCustodianBean.lstAllFundType}"
													   var="fundType" itemLabel="#{fundType.strFundType}" itemValue="#{fundType.strFundType}"/>
										<p:ajax event="change" update="somFundCUI, msgFundType, msgFundType" listener="#{portafolioDetailCustodianBean.getFundCUI()}" />
										<f:validator validatorId="com.pradera.commons.view.validators.SelectOneMenuValidator" />
									</p:selectOneMenu>
									<p:message id="msgFundType" for="somFundType" display="icon" />
									</h:panelGrid>									
								</td>
							</tr>
								
							<tr>
								<td>
									<h:outputText value="#{msgs['lbl.custody.detail.afp.and.insurance.fund.cui']} (*)" styleClass="required-field" id="otFundCUI"/>
								</td>
								<td >
									<h:panelGrid columns="2">
										<p:selectOneMenu id="somFundCUI" value="#{portafolioDetailCustodianBean.holderHelper.fundCUI}" style="width:310px"
														 label="#{msgs['lbl.custody.detail.afp.and.insurance.fund.cui']}">
											<f:selectItem itemLabel="#{msgs['cbo.opt.all']}" id="siFundCUI"/>
											<f:selectItems id="siLstFundCUI" value="#{portafolioDetailCustodianBean.lstFoundCUI}"
														   var="fundCUI" itemLabel="#{fundCUI.fullName}" itemValue="#{fundCUI.fundCUI}" />
											<f:validator validatorId="com.pradera.commons.view.validators.SelectOneMenuValidator" />
											<p:ajax event="change" update="msgFundCUI"/>			
										</p:selectOneMenu>
										<p:message id="msgFundCUI" for="somFundCUI" display="icon" />		
									</h:panelGrid>					
								</td>
								
								<td>
									<h:outputText value="#{msgs['lbl.reportlogger.execDate']} (*)" styleClass="required-field"/>
								</td>
								<td>
									<p:calendar id="calDate" showOn="both" readonlyInput="true" size="10" navigator="true"
												value="#{portafolioDetailCustodianBean.holderHelper.date}"				
												pattern="#{msgs['dateFormat']}" maxdate="#{portafolioDetailCustodianBean.holderHelper.date}">					
									</p:calendar>
								</td>
							</tr>
							
							<tr>
								<td colspan="6" align="center">
									<p:commandButton id="cbSend" value="#{msgs['btn.send']}" icon="ui-send" process="@form" 
													 update="somEconomicActivity, somFundType, somFundCUI, msgEconomicActivity, msgFundType, msgFundCUI :opnlGenericDialogs"
													 actionListener="#{portafolioDetailCustodianBean.submitForm()}">
										<f:param name="skipValidation" value="true"/>	
									</p:commandButton>
									<p:commandButton id="cbClean" value="#{msgs['btn.clean']}" icon="fa fa-trash" process="@this" update="@form" 
													 action="#{portafolioDetailCustodianBean.clean}"/>
								</td>
							</tr>
						</table>
					</p:fieldset>
				</td>
			</tr>
		</table>
		<p:confirmDialog id="reportGenerationOk" widgetVar="reportGenerationOkWidget" severity="info" rendered="false" visible="true"
						 closable="false" header="#{headerMessageView}" message="#{bodyMessageView}">
			<p:commandButton id="cmbConfirmOk" value="#{msgs['btn.accept']}" type="reset" onclick="reportGenerationOkWidget.hide()"/>
		</p:confirmDialog>
</h:form>
<p:outputPanel id="opnlDialogs">
</p:outputPanel>
	</ui:define>
</ui:composition>
</html>

iReports/src/main/webapp/pages/acccounts/custodyDetailAgbSafiFicReport.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:pe="http://primefaces.org/ui/extensions"
	xmlns:ark="http://java.sun.com/jsf/composite/privilegesPanel"
	xmlns:arkHelp="http://java.sun.com/jsf/composite/helperExtension">

<ui:composition template="/template/default.xhtml">
<ui:define name="body">
<style type="text/css">
.ui-datatable tbody td{searchHolderByCode
	white-space: normal !important;
}
</style>
	<h:outputText value="#{msgs['title.Report']}" styleClass="title-page" id="idTitle"/>
	<h:form id="frmCustodyDetail">
		<table width="100%">
			<tr>
				<td>
					<p:fieldset legend="#{msgs['lbl.custody.detail.agb.safi.fic.legend']}" id="fsMainLegend">
						<table width="100%" border="0"> 
							<tr>
								<td width="120px">
									<h:outputText value="#{msgs['lbl.format.report']}" />
								</td>
								<td width="450px">
									<p:selectOneMenu value="#{custodyDetailAgbAndSafiAndFicBean.reportUser.reportFormat}" required="true">
										<f:selectItems value="#{custodyDetailAgbAndSafiAndFicBean.reportFormats}" var="format" 
													   itemLabel="#{format.parameterName}" itemValue="#{format.parameterTablePk}"/>
									</p:selectOneMenu>
								</td>
							</tr>
							<ui:remove>
							 <tr>
								<td>
									<h:outputText value="#{msgs['lbl.custody.detail.afp.and.insurance.economic.act']}" id="otEconomicActivity"/>
								</td>
								<td>
									<h:panelGrid columns="2">
										<p:selectOneMenu id="somEconomicActivity" style="width:310px" 
														 label="#{msgs['lbl.custody.detail.afp.and.insurance.economic.act']}"
														 value="#{custodyDetailAgbAndSafiAndFicBean.holderHelper.economicActivity}">
											<f:selectItem itemLabel="#{msgs['cbo.opt.all']}"/>
											<f:selectItems id="siEconomicActivity" value="#{custodyDetailAgbAndSafiAndFicBean.lstEconomicActivity}"
														   var="economicAct" itemLabel="#{economicAct.description}" itemValue="#{economicAct.parameterTablePk}"/>
												<p:ajax event="change" update="somFundCUI"
														listener="#{custodyDetailAgbAndSafiAndFicBean.getFunds()}" />	
											<f:validator validatorId="com.pradera.commons.view.validators.SelectOneMenuValidator" />
											<f:param name="skipValidation" value="false"/>
										</p:selectOneMenu>
									</h:panelGrid>								
								</td>
								
								<td width="120px">
									<h:outputText value="#{msgs['lbl.custody.detail.afp.and.insurance.fund.cui']}" id="otFundCUI"/>
								</td>
								<td >
									<h:panelGrid columns="2">
										<p:selectOneMenu id="somFundCUI" value="#{custodyDetailAgbAndSafiAndFicBean.holderHelper.fundCUI}" 
														 style="width:310px" disabled="#{custodyDetailAgbAndSafiAndFicBean.blDisabled}">
											<f:selectItem itemLabel="#{msgs['cbo.opt.all']}" id="siFundCUI"/>
											<f:selectItems id="siLstFundCUI" value="#{custodyDetailAgbAndSafiAndFicBean.lstFoundCUI}"
														   var="fundCUI" itemLabel="#{fundCUI.fullName}" itemValue="#{fundCUI.fundCUI}" />										
										</p:selectOneMenu>
									</h:panelGrid>					
								</td>
							</tr>
							</ui:remove>
							<tr>
								<ui:remove>
								<td>
									<h:outputText value="#{msgs['lbl.custody.detail.afp.and.insurance.security.code']}" id="otSecurityPk"/>
								</td>
								<td>
									<h:panelGrid columns="3">
										<p:inputText id="itSecurity" size="15" maxlength="12" widgetVar="wvSecurity" 
													 value="#{custodyDetailAgbAndSafiAndFicBean.holderHelper.securityTO.securitiesCode}">
											<p:keyFilter regEx="#{gconst['helper.securities.alphanumeric.not.space']}" preventPaste="false"/>
											<p:ajax event="blur" partialSubmit="true" process="@this" update="itSecurity, itSecDesc"
													listener="#{custodyDetailAgbAndSafiAndFicBean.searchSecurityByCode()}"/>
										</p:inputText>
										<p:outputPanel id="securitiesHelper">
											<arkHelp:security security="#{custodyDetailAgbAndSafiAndFicBean.holderHelper.securityTO}" process="@this"
															  update="frmCustodyDetail:itSecurity frmCustodyDetail:itSecDesc"/>
										</p:outputPanel>
										<p:inputText size="40" id="itSecDesc" disabled="true"
													 value="#{custodyDetailAgbAndSafiAndFicBean.holderHelper.securityTO.description}" />
									</h:panelGrid>
								 </td>
								 </ui:remove>
								 
								 <td>
									<h:outputText value="#{msgs['lbl.reportlogger.execDate']} (*)" styleClass="required-field"/>
								</td>
								<td>
									<p:calendar id="calDate" showOn="both" readonlyInput="true" size="10" navigator="true"
												value="#{custodyDetailAgbAndSafiAndFicBean.holderHelper.date}"						
												pattern="#{msgs['dateFormat']}" maxdate="#{custodyDetailAgbAndSafiAndFicBean.holderHelper.date}">					
									</p:calendar>
								</td>
							</tr>
							<tr><td height="20px"></td></tr>
							<tr>
								<td colspan="6" align="center">
									<p:commandButton id="cbSend" value="#{msgs['btn.send']}" icon="ui-send"  process="@form" update=":opnlGenericDialogs"
													 actionListener="#{custodyDetailAgbAndSafiAndFicBean.submitForm()}">
									</p:commandButton>
									<p:commandButton id="cbClean" value="#{msgs['btn.clean']}" icon="fa fa-trash" process="@this" update="@form" 
													 action="#{custodyDetailAgbAndSafiAndFicBean.clean}"/>
								</td>
							</tr>
						</table>
					</p:fieldset>
				</td>
			</tr>
		</table>
		<p:confirmDialog id="reportGenerationOk" widgetVar="reportGenerationOkWidget" severity="info" rendered="false" visible="true"
						 closable="false" header="#{headerMessageView}" message="#{bodyMessageView}">
			<p:commandButton id="cmbConfirmOk" value="#{msgs['btn.accept']}" type="reset" onclick="reportGenerationOkWidget.hide()"/>
		</p:confirmDialog>
</h:form>
<p:outputPanel id="opnlDialogs">
</p:outputPanel>
	</ui:define>
</ui:composition>
</html>